# Generated by Django 3.0.6 on 2022-09-01 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220901_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 9, 41, 27, 209488, tzinfo=utc)),
        ),
    ]
