# Generated by Django 3.0.6 on 2022-09-01 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220901_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 9, 51, 18, 870962, tzinfo=utc)),
        ),
    ]
